#!/usr/bin/env bash

# delete files only used to build:
# program.sh and init.sh

projectdir=$1

[[ -d $projectdir/wiki ]] \
  && mv "$projectdir/___wikihome" "$projectdir/wiki/Home.md"

rm -f "$projectdir"/___{version,wikihome,envs,help,getopt}

cp -f -t "$projectdir/next"                 \
         "$projectdir/README.md"            \
         "$projectdir/LICENSE"              \
         "$projectdir/${projectdir##*/}.1"  \


cp -f "$projectdir/program.sh"              \
      "$projectdir/next/${projectdir##*/}.bash"
